name: "Terraform Destroy"

on:
  push:
    branches:
      - main

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "learn-terraform-github-actions"
  CONFIG_DIRECTORY: "./"

jobs:
  terraform:
    if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace Select
        run: terraform workspace select ${{ env.TF_WORKSPACE }}

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan

      - name: Terraform Apply (Destroy)
        run: terraform apply -input=false tfplan
        env:
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

          
# name: "Terraform Destroy"

# on:
#   push:
#     branches:
#       - main

# env:
#   TF_CLOUD_ORGANIZATION: "ZEW" # change as needed
#   TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
#   TF_WORKSPACE: "learn-terraform-github-actions"
#   CONFIG_DIRECTORY: "./"

# jobs:
#   terraform:
#     if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
#     name: "Terraform Destroy"
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Upload Configuration
#         uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
#         id: destroy-upload
#         with:
#           workspace: ${{ env.TF_WORKSPACE }}
#           directory: ${{ env.CONFIG_DIRECTORY }}

#       - name: Create Destroy Run
#         uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
#         id: destroy-run
#         with:
#           workspace: ${{ env.TF_WORKSPACE }}
#           configuration_version: ${{ steps.destroy-upload.outputs.configuration_version_id }}
#           is_destroy: true  # This flag ensures a destroy run is created

#       - name: Destroy
#         uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
#         if: fromJSON(steps.destroy-run.outputs.payload).data.attributes.actions.IsConfirmable
#         id: destroy
#         with:
#           run: ${{ steps.destroy-run.outputs.run_id }}
#           comment: "Destroy Run from GitHub Actions CI ${{ github.sha }}"
